version: '3'
services:
  laravel:
    build: 
      context: .
      dockerfile: './php-fpm/dev.dockerfile'
    container_name: gym-app
    volumes:
      - ./src:/var/www/html
    image: gym-app
    depends_on:
      - mysql
      - base

  base:
    build:
      context: .
      dockerfile: './php-fpm/base.dockerfile'
    container_name: gym-app-base
    image: gym-app-base

  nginx:
    image: nginx:latest
    container_name: gym-nginx
    volumes:
      - ./src/public:/var/www/html/public
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 90:80
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: gym-mysql
    ports:
      - 6033:3306
    volumes:
      - gym-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=gym
      - MYSQL_ROOT_PASSWORD=password

volumes:
  gym-data:
    driver: local
