version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - docker-cache-{{ checksum "nginx/Dockerfile" }}-{{ checksum "src/composer.lock" }}-{{ checksum "src/package.json" }}
          paths:
            - ~/caches/images.tar
      - run:
          command: |
            if [[ -e ~/caches/images.tar ]]; then
              docker load -i ~/caches/images.tar
            fi
          name: docker load
      - run:
          command: docker-compose up -d --build
          name: docker up
      - run:
          command: mkdir -p ~/caches
          name: mkdir -p ~/caches
      - run:
          command: |
            if [[ ! -e ~/caches/images.tar ]]; then
              docker save -o ~/caches/images.tar $(docker images --filter "dangling=false" --format "{{.Repository}}:{{.Tag}}")
            fi
          name: docker save
      - save_cache:
          key: docker-cache-{{ checksum "nginx/Dockerfile" }}-{{ checksum "src/composer.lock" }}-{{ checksum "src/package.json" }}
          paths:
            - ~/caches/images.tar
  
  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - docker-cache-{{ checksum "nginx/Dockerfile" }}-{{ checksum "src/composer.lock" }}-{{ checksum "src/package.json" }}
          paths:
            - ~/caches/images.tar
      - run:
          command: |
            if [[ -e ~/caches/images.tar ]]; then
              docker load -i ~/caches/images.tar
            fi
          name: docker load
      - run: 
          command: docker-compose run laravel vendor/bin/phpunit
          name: test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
